spring:
  main:
    web-application-type: reactive
server:
  host: localhost
  port: 8082
resilience4j.ratelimiter:
  instances:
    basic:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
    polite:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
    impolite:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
  metrics:
    enabled: true
  configs:
    default:
      registerHealthIndicator: true
logging:
  level:
    root: OFF
    io:
      github:
        resilience4j:
          ratelimiter: OFF
    org:
      springframework:
        boot:
          autoconfigure:
            web:
              reactive:
                error: OFF

