spring:
  main:
    web-application-type: reactive
  cloud:
    gcp:
      spanner:
        instance-id: example-spanner
        database: example
security:
  basic:
    enable: false
  ignored: /**
server:
  host: localhost
  port: 8080
resilience4j.ratelimiter:
  instances:
    basic:
      limitForPeriod: 1
      limitRefreshPeriod: 1s
  metrics:
    enabled: true
  configs:
    default:
      registerHealthIndicator: true
